version: "3.8"
services:
  nuxt:
    container_name: docker-nuxt-template
    build:
      context: .
      dockerfile: ./infra/docker/nuxt/Dockerfile
      args:
        WORKDIR: "/home/ec2-user/code/nuxt"
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    volumes:
      - ./:/home/ec2-user/code
      # for mac github config
      - ~/.ssh:/root/.ssh
