version: "3.8"
services:
  nuxt:
    container_name: care-record-dashboard-nuxt
    build:
      context: .
      dockerfile: ./infra/docker/nuxt/Dockerfile
      args:
        WORKDIR: "/home/ec2-user/nuxt"
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./nuxt:/home/ec2-user/nuxt

